name: change_copy  # Project identifier; keep unchanged for compatibility
description: "A second copy of the original app."
publish_to: 'none'

version: 1.0.0+3

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.12.0
  cupertino_icons: ^1.0.2
  uuid: ^4.5.1  # Updated to latest version
  shared_preferences: ^2.5.3
  path_provider: ^2.0.0  # Keep aligned with existing path helpers
  permission_handler: ^12.0.1  # Updated to latest major version
  device_info_plus: ^12.2.0
  sqflite: ^2.4.2  # Updated to latest version
  path: ^1.8.0
  image_picker: ^1.2.0  # Latest compatible picker
  photo_manager: ^3.7.1
  video_player: ^2.10.0
  url_launcher: ^6.3.2
  video_thumbnail: ^0.5.3
  chewie: ^1.13.0  # Updated to latest version
  flutter_colorpicker: ^1.0.3
  archive: ^4.0.7
  file_picker: ^10.3.3  # Updated to latest major version
  share_plus: ^12.0.1  # Updated to latest major version
  win32: ^5.15.0
  audioplayers: ^6.5.1
  record: ^6.1.2  # Updated to latest major version
  crypto: ^3.0.3  # Hash utilities
  webview_flutter: ^4.13.0  # Updated to latest version
  flutter_downloader: ^1.12.0
  http: ^1.5.0
  dio: ^5.9.0  # Updated to latest version
  reorderable_grid_view: ^2.2.8
  teledart: ^0.6.1  # Telegram bot client - keep current version for compatibility
  html: ^0.15.6
  mime: ^2.0.0  # Updated to latest major version
  intl: ^0.20.2  # Updated to latest version
  flutter_svg: ^2.2.1
  flutter_background_service: ^5.0.5
  flutter_background_service_android: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/icon/icon.png
    - assets/media/
    - assets/icon/weather_sunny.svg
    - assets/icon/weather_cloudy.svg
    - assets/icon/weather_rain.svg
    - assets/icon/weather_snow.svg
    - assets/icon/weather_fog.svg
    - assets/icon/weather_wind.svg
    - assets/icon/weather_thunder.svg
    - assets/icon/weather_haze.svg
    - assets/icon/mood_happy.svg
    - assets/icon/mood_calm.svg
    - assets/icon/mood_sad.svg
    - assets/icon/mood_angry.svg
    - assets/icon/mood_excited.svg
    - assets/icon/mood_depressed.svg
    - assets/icon/mood_surprised.svg
    - assets/icon/mood_neutral.svg

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  remove_alpha_ios: true
