name: change_copy  # Project identifier; keep unchanged for compatibility
description: "A second copy of the original app."
publish_to: 'none'

version: 1.0.0+3

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.1.0
  cupertino_icons: ^1.0.2
  uuid: ^3.0.4  # Matches legacy data assumptions
  shared_preferences: ^2.3.2
  path_provider: ^2.0.0  # Keep aligned with existing path helpers
  permission_handler: ^11.3.0  # Runtime permission handling
  device_info_plus: ^11.3.0
  sqflite: ^2.0.0+4  # Stable with current SQL schema
  path: ^1.8.0
  image_picker: ^1.2.0  # Latest compatible picker
  photo_manager: ^3.5.1
  video_player: ^2.10.0
  url_launcher: ^6.2.5
  video_thumbnail: ^0.5.3
  chewie: ^1.7.1  # Material video controls
  flutter_colorpicker: ^1.0.3
  archive: ^4.0.4
  file_picker: ^9.0.2
  share_plus: ^10.1.1
  win32: ^5.8.0
  audioplayers: ^6.4.0
  record: ^5.2.1
  crypto: ^3.0.3  # Hash utilities
  webview_flutter: ^4.4.4
  flutter_downloader: ^1.11.6
  http: ^1.2.0
  dio: ^5.4.0
  reorderable_grid_view: ^2.2.8
  teledart: 0.6.1  # Telegram bot client
  html: ^0.15.4
  mime: ^1.0.4
  intl: ^0.18.1
  flutter_svg: ^2.0.10
  flutter_background_service: ^5.0.5
  flutter_background_service_android: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon/icon.png
    - assets/media/
    - assets/icon/weather_sunny.svg
    - assets/icon/weather_cloudy.svg
    - assets/icon/weather_rain.svg
    - assets/icon/weather_snow.svg
    - assets/icon/weather_fog.svg
    - assets/icon/weather_wind.svg
    - assets/icon/weather_thunder.svg
    - assets/icon/weather_haze.svg
    - assets/icon/mood_happy.svg
    - assets/icon/mood_calm.svg
    - assets/icon/mood_sad.svg
    - assets/icon/mood_angry.svg
    - assets/icon/mood_excited.svg
    - assets/icon/mood_depressed.svg
    - assets/icon/mood_surprised.svg
    - assets/icon/mood_neutral.svg

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  remove_alpha_ios: true
