name: Local Config
version: 1.0.0
schema: v1

models:
  - name: DeepSeek
    provider: openai
    model: deepseek-chat
    apiKey: sk-MHM4j6vRJZtd6o7VIpIZngU0NMpmDUzQIa3S6ZuS7tkM48wQ
    apiBase: https://xinyuanai666.com/v1
    roles:
      - chat
      - autocomplete
    defaultCompletionOptions:
      temperature: 0.2
      maxTokens: 1024
  - name: Grok-4.1-fast
    provider: openai
    model: grok-4.1-fast
    apiKey: sk-i4TOLmt4SB9ccIRIzigyGUkoTh52D6NsiR2PUePKXAefrBeX
    apiBase: https://xinyuanai666.com/v1
    roles:
      - chat
      - autocomplete
    defaultCompletionOptions:
      temperature: 0.2
      maxTokens: 1024